"""Add language and unit_system preferences to user model.

Revision ID: 1a2b3c4d5e6f
Revises: f1a2b3c4d5e7
Create Date: 2025-05-03 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = 'bc23de45fa67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.String(5), nullable=False, server_default='en'))
    op.add_column('user', sa.Column('unit_system', sa.String(10), nullable=False, server_default='metric'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'unit_system')
    op.drop_column('user', 'language')
    # ### end Alembic commands ###
