"""Add PasswordResetOTP model

Revision ID: 383b97d8277f
Revises: 510931190d74
Create Date: 2026-02-13 00:52:58.916415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383b97d8277f'
down_revision = '510931190d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_otp',
    sa.Column('otp_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('otp_id')
    )
    with op.batch_alter_table('password_reset_otp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_otp_user_email'), ['user_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_otp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_otp_user_email'))

    op.drop_table('password_reset_otp')
    # ### end Alembic commands ###
