"""Change blood_pressure from string to float

Revision ID: 393e4c73d73e
Revises: f496b9e8af03
Create Date: 2026-01-19 01:32:49.128114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393e4c73d73e'
down_revision = 'f496b9e8af03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_data', schema=None) as batch_op:
        batch_op.alter_column('blood_pressure',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_data', schema=None) as batch_op:
        batch_op.alter_column('blood_pressure',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
