"""drop medication_id collumn in alert

Revision ID: 4af451598bbe
Revises: 7cbf1d5f606b
Create Date: 2026-02-14 13:32:38.484115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af451598bbe'
down_revision = '7cbf1d5f606b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('medication_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medication_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'medication', ['medication_id'], ['medication_id'])

    # ### end Alembic commands ###
