"""Change frequency of medication to Integer

Revision ID: 510931190d74
Revises: 393e4c73d73e
Create Date: 2026-01-19 17:13:00.751939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510931190d74'
down_revision = '393e4c73d73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
