"""Add ml_predicted_health_score to health_data

Revision ID: 52c26be4e468
Revises: 66433565aa81
Create Date: 2026-03-01 23:26:44.248141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c26be4e468'
down_revision = '66433565aa81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ml_predicted_health_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_data', schema=None) as batch_op:
        batch_op.drop_column('ml_predicted_health_score')

    # ### end Alembic commands ###
