"""Remove unique constraint from medication table

Revision ID: 66433565aa81
Revises: 8ef2f2b4fa1d
Create Date: 2026-02-15 01:46:08.616724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66433565aa81'
down_revision = '8ef2f2b4fa1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_medicine'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_medicine'), ['user_id', 'medicine_id'])

    # ### end Alembic commands ###
