"""Added is_critical to medication model

Revision ID: 8ef2f2b4fa1d
Revises: 4af451598bbe
Create Date: 2026-02-14 22:40:23.858930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef2f2b4fa1d'
down_revision = '4af451598bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_critical', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.drop_column('is_critical')

    # ### end Alembic commands ###
