"""add health score and risk columns to health_data

Revision ID: f496b9e8af03
Revises: 9de5942fba0d
Create Date: 2026-01-18 13:06:26.793687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f496b9e8af03'
down_revision = '9de5942fba0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rule_based_risk_label', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ml_predicted_risk_label', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_data', schema=None) as batch_op:
        batch_op.drop_column('ml_predicted_risk_label')
        batch_op.drop_column('rule_based_risk_label')
        batch_op.drop_column('health_score')

    # ### end Alembic commands ###
